### ISSUE TITLE
[Question] Does this support breakpoints on activities that are invoked via proxyActivities

### ISSUE THREAD

**Issue by efreethy** [temporalio/vscode-debugger-extension#70]
I was able to set breakpoints in the workflow itself, however there are callouts to activity functions that are proxied via proxyActivities, and I cannot setup break points in those activities.

Is there a way to work around this?

Thanks

**Comment by lorensr** [comment]
No, it’s just a workflow history replayer, which doesn’t actually call activities, just uses the return values in history. I just clarified this here: https://github.com/temporalio/vscode-debugger-extension/pull/60

For debugging activities, see here: https://github.com/temporalio/samples-typescript/issues/319
